added logic for determining PR in CodeQL advanced context

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -40,6 +40,22 @@ runs:
         echo RUN_PATH: $RUN_PATH
         echo "action-run-path=$RUN_PATH" >> $GITHUB_OUTPUT
 
+        triggering_event=head_sha=${{ github.event.workflow_run.event }}
+        head_branch=${{ github.event.workflow_run.head_branch }}
+
+        echo "triggering_event=$triggering_event"
+        echo "head_branch=$head_branch"
+
+        if [[ "$triggering_event" == "pull_request" ]]; then
+          PR_NUMBER=${{ github.event.workflow_run.pull_requests.number }}
+        elsif [[ "$triggering_event" == "dynamic" && "$head_branch" == *"/pull/"* ]]; then
+          # Extract the PR number from the head_branch
+          PR_NUMBER=$(echo $head_branch | cut --delimiter='/' --fields=3 )
+        else
+          echo "Error: Unable to determine PR number from the triggering event. Please check if the triggering event is a PR."
+          exit 1
+        fi
+
         #Getting the pr-number
         PR_NUMBER=$(echo ${{github.event.workflow_run.head_branch}} | cut --delimiter='/' --fields=3 )
         echo PR_NUMBER: $PR_NUMBER
